name: eureka-doom-editor
version: 1.24
grade: stable
summary: Eureka is a map editor for the classic DOOM games.
description: |
  Eureka is a map editor for the classic DOOM games, and a few related games such as Heretic and Hexen. The supported operating systems are: Linux (and other Unices), Windows and OS X.

  Eureka is free software under the GNU General Public License (GPL). Please note that it comes with absolutely NO WARRANTY of any kind. 

  Features

   - Undo/Redo (multiple levels)
   - 3D preview
   - Low system requirements, no 3D card required
   - Editable panels for things, linedefs, sectors (etc)
   - Browser for textures, flats, things (etc)
   - Key binding system
   - Built-in nodes builder 

  Supported Games

   - DOOM
   - DOOM 2
   - Final Doom
   - FreeDoom
   - HacX
   - Heretic
   - Hexen
   - Strife
  
  To enable "Test in Game" functionality in the editor set either of the following absolute paths as "Exe path", depending on your distribution:
    /snap/eureka-doom-editor/current/doom-engine/bin/prboom-plus-iwad-launch
    /var/lib/snapd/snap/eureka-doom-editor/current/doom-engine/bin/prboom-plus-iwad-launch
   
  If no DOOM engine is present install the prboom-plus-beidl snap and connect the interface, ie:
   snap install prboom-plus-beidl
   snap connect eureka-doom-editor:doom-engine prboom-plus-beidl:doom-engine

confinement: strict

apps:
  eureka:
    command: desktop-launch eureka-editor
    plugs: [ x11, desktop, opengl, pulseaudio, home, removable-media ]

plugs:
  doom-engine:
    content: doom-engine
    interface: content
    target: $SNAP/doom-engine
    default-provider: prboom-plus-beidl:doom-engine

parts:
  eureka:
    source: https://sourceforge.net/projects/eureka-editor/files/Eureka/1.24/eureka-124-source.tar.gz/download
    source-type: tar
    source-checksum: sha1/c5c6374fec532d0903b45bc5ce5b806740d6cbc2
    plugin: make
    override-pull: |
      snapcraftctl pull
      sed -i 's|/usr/local|/usr|g' Makefile
      sed -i 's|xdg-desktop-menu|\#xdg-desktop-menu|g' Makefile
      sed -i 's|xdg-icon-resource|\#xdg-icon-resource|g' Makefile
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      snapcraftctl build
    build-packages:
      - make
      - libfltk1.3-dev
      - zlib1g-dev
      - xdg-utils
      - libjpeg-turbo8-dev
      - libgl1-mesa-dev
      - libx11-xcb-dev
      - libxft-dev
      - libxi-dev
    after: [ desktop-gtk2 ]
  wrapper:
    plugin: dump
    organize:
      eureka-editor: usr/bin/eureka-editor
    after: [ env ]
  env:
    plugin: nil
    stage-packages:
      - libfltk1.3
      - libfltk-images1.3
      - zlib1g
      - libjpeg-turbo8
    after: [ eureka ]
