name: eureka-doom-editor
version: 1.21
summary: Eureka is a map editor for the classic DOOM games.
description: |
  Eureka is a map editor for the classic DOOM games, and a few related games such as Heretic and Hexen. The supported operating systems are: Linux (and other Unices), Windows and OS X.

  Eureka is free software under the GNU General Public License (GPL). Please note that it comes with absolutely NO WARRANTY of any kind. 

  Features

   - Undo/Redo (multiple levels)
   - 3D preview
   - Low system requirements, no 3D card required
   - Editable panels for things, linedefs, sectors (etc)
   - Browser for textures, flats, things (etc)
   - Key binding system
   - Built-in nodes builder 

  Supported Games

   - DOOM
   - DOOM 2
   - Final Doom
   - FreeDoom
   - HacX
   - Heretic
   - Hexen
   - Strife 

confinement: strict

apps:
  eureka-doom-editor:
    command: desktop-launch eureka
    plugs: [ wayland, x11, desktop, opengl, home ]

parts:
  eureka-doom-editor:
    source: https://sourceforge.net/projects/eureka-editor/files/Eureka/1.21/eureka-121-source.tar.gz/download
    source-type: tar
    source-checksum: sha1/bb00bcda68a6974b158f06b82abba337b5b919f0
    plugin: make
    override-pull: |
      snapcraftctl pull
      sed -i 's|\$(PREFIX)/bin/|\$(DESTDIR)\$(PREFIX)/bin/|g' Makefile
      sed -i 's|INSTALL_DIR=|INSTALL_DIR=\$(DESTDIR)|g' Makefile
      sed -i 's|/usr/local|/usr|g' Makefile
      sed -i 's|xdg-desktop-menu|\#xdg-desktop-menu|g' Makefile
      sed -i 's|xdg-icon-resource|\#xdg-icon-resource|g' Makefile
    build-packages:
      - make
      - libfltk1.3-dev
      - zlib1g-dev
      - xdg-utils
      - libjpeg-turbo8-dev
    after: [ desktop-gtk2 ]
  env:
    plugin: nil
    stage-packages:
      - libfltk1.3
      - zlib1g
      - libjpeg-turbo8
    after: [ eureka-doom-editor ]
